### ISSUE TITLE
Object(...) is not a function 

### ISSUE THREAD

**Issue by hiteshsahu** [namannehra/flipping-pages#2] opened 2019-01-09 15:40 UTC
https://codesandbox.io/s/p9477l2jlj

**Comment by namannehra** [comment] 2019-01-09 17:54
The problem only seems to happen when you use create-react-app template on codesandbox. Works fine with the default template (parcel). Also works fine with create-react-app on my computer. Here is a working codesandbox example https://codesandbox.io/s/z685kk773.

I think the problem is caused by me not using semicolons and then the minifier not doing correct automatic semicolon insertion. I'll look into it.

Can you try it on your computer locally and let me know if it works?

**Comment by namannehra** [comment] 2019-01-10 09:45
@hiteshsahu The error in the codesandbox you sent is caused by outdated dependencies. Update the dependencies and it'll work fine. Also add `direction` prop to `FlippingPages` as it's required. Here is a codesandbox with the fixes https://codesandbox.io/s/8xv05lwzx0. I'm closing this issue. Let me know you have any other problem.

**Closed as completed by namannehra** 2019-01-10 09:45 UTC
